### ISSUE TITLE
Macao does not commonly use postal codes

### ISSUE THREAD

**Issue by iamEAP** [tableau-mkt/addressfield.json#35]
Macao Post's standard address format notes that postal codes should appear "if applicable." (http://www.macaupost.gov.mo/Contents/AddressFormat.aspx?lang=en-us)

Most folks on the Internet seem to agree that it's not commonly used.

Google's API agrees: http://i18napis.appspot.com/address/data/MO

**Comment by violalee** [comment]
Closing this in 8/28 in ticket clean-up session with Eric.
